#!/bin/bash
[ "$UID" -eq 0 ] || exec sudo HOME=$HOME "$0" -u ${USER}

mkdir /etc/skel/.config

cp -rL zsh-plugins /etc/skel
cp -rL .zshrc /etc/skel
cp -rL .oh-my-zsh /etc/skel
cp -rL .tmux.conf /etc/skel
cp -rL .vimrc /etc/skel
cp -rL .vim /etc/skel
cp -rL coc /etc/skel/.config
cp -rL .cowrc /etc/skel/
cp -rL .cowfiles /etc/skel/
