#!/bin/bash
set -e

echo "$(whoami)"

[ "$UID" -eq 0 ] || exec sudo HOME=$HOME "$0" "$@"

echo "Installing to home directory: $HOME"

declare -A osInfo;
osInfo[/etc/debian_version]="apt-get install -y"
osInfo[/etc/alpine-release]="apk --update add"
osInfo[/etc/centos-release]="yum install -y"
osInfo[/etc/fedora-release]="dnf install -y"

for f in ${!osInfo[@]}
do
    if [[ -f $f ]];then
        package_manager=${osInfo[$f]}
    fi
done

packages="git tmux zsh vim curl tree nodejs npm"

${package_manager} ${package} || true

# TODO check $HOME is set, if not error out

# TODO chsh to zsh

# TODO vim 
# airline?, ctrlp, vim surround, matchit

mkdir -p $HOME/.vim/pack/colors
mkdir -p $HOME/.vim/backupdir
mkdir -p $HOME/.vim/swapdir

RCFILESDIR=$PWD

ln -sfn $RCFILESDIR/.zshrc $HOME/.zshrc
ln -sfn $RCFILESDIR/zsh-plugins $HOME/zsh-plugins
ln -sfn $RCFILESDIR/.oh-my-zsh $HOME/.oh-my-zsh
ln -sfn $RCFILESDIR/.vimrc $HOME/.vimrc
ln -sfn $RCFILESDIR/.tmux.conf $HOME/.tmux.conf
ln -sfn $RCFILESDIR/.vim/pack $HOME/.vim/pack
ln -sfn $RCFILESDIR/.vim/colors $HOME/.vim/colors
