#!/bin/bash
set -e
set -x

if [[ -z $HOME ]];then
    echo "must have a home directory!"
fi

echo "$(whoami)"

[ "$UID" -eq 0 ] || exec sudo HOME=$HOME "$0" -u ${USER}

getopts ":u:" u
case $u in
    u)
        CALLING_USER=$OPTARG
        ;;
    *)
        echo "dont run as root, just run and let me do it"
        exit 1
esac

echo "Installing to home directory: $HOME"

declare -A osInfo;
apt="apt-get install -y"
osInfo[/etc/debian_version]=$apt
apk="apk --update add"
osInfo[/etc/alpine-release]=$apk
yum="yum install -y"
osInfo[/etc/centos-release]=$yum
dnf="dnf install -y"
osInfo[/etc/fedora-release]=$dnf

for f in ${!osInfo[@]}
do
    if [[ -f $f ]];then
        package_manager=${osInfo[$f]}
    fi
done

if [ $package_manager = $apt ]; then
    platform_packages="fortunes-debian-hints debian-handbook"
fi

optional_stupid_packages="figlet lolcat"
packages="git tmux zsh vim curl tree nodejs npm imagemagic chroma fzf man2html \
ruby info2www fortune $platform_packages $optional_stupid_packages"

${package_manager} ${package} || true

gem install mdless

# Enable apache cgi (for man2html)
a2enmod cgid

mkdir -p $HOME/.vim/pack/colors
mkdir -p $HOME/.vim/backupdir
mkdir -p $HOME/.vim/swapdir

RCFILESDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

mkdir -p $HOME/.vim/swapdir
mkdir -p $HOME/.vim/backupdir
mkdir -p $HOME/.config/coc

ln -sfn $RCFILESDIR/.zshrc $HOME/.zshrc
ln -sfn $RCFILESDIR/zsh-plugins $HOME/zsh-plugins
ln -sfn $RCFILESDIR/.oh-my-zsh $HOME/.oh-my-zsh
ln -sfn $RCFILESDIR/.vimrc $HOME/.vimrc
ln -sfn $RCFILESDIR/.tmux.conf $HOME/.tmux.conf
ln -sfn $RCFILESDIR/.vim/pack $HOME/.vim/pack
ln -sfn $RCFILESDIR/.vim/colors $HOME/.vim/colors
ln -sfn $RCFILESDIR/.vim/coc
ln -sfn $RCFILESDIR/.config/coc $HOME/.config/coc
ln -sfn $RCFILESDIR/.cowrc $HOME/.cowrc
ln -sfn $RCFILESDIR/.cowfiles $HOME/.cowfiles

chsh -s `which zsh` $CALLING_USER
