#!/bin/bash
[ "$UID" -eq 0 ] || exec sudo HOME=$HOME "$0" -u ${USER}

sudo cp -RL $HOME/.zshrc /root/
sudo cp -RL $HOME/.oh-my-zsh /root/
sudo cp -RL $HOME/zsh-plugins /root/
sudo cp -RL $HOME/.tmux.conf /root/
sudo cp -RL $HOME/.vimrc /root/
sudo cp -RL $HOME/.vim /root/
sudo cp -RL $HOME/.cowfiles /root/
sudo cp -RL $HOME/.cowrc /root/
sudo cp -RL $HOME/.emacs.d /root/
sudo cp -RL $HOME/.doom.d /root/

chown -R root /root

chsh -s `which zsh` root
