#+TITLE: Doom Emacs Literate Configuration
#+DESCRIPTION: I though this might be easier to read and find things,
#+DESCRIPTION+: especially if I'm lazy and dont make seperate files in the future
#+STARTUP: content

* General Doom/Emacs Setup
** Personal Information
User information, used for git, email, templates, etc.
#+begin_src elisp
;; Some functionality uses this to identify you, e.g. GPG configuration, email
;; clients, file templates and snippets.
(setq user-full-name "Brandon Pollack"
      user-mail-address "brandonpollack23@gmail.com")
#+end_src

this file. Emacs searches the `load-path' when you load packages with
`require' or `use-package'.
** Global Options
#+begin_src elisp
(setq
 ;; Evil emacs mode cursor tells me it isn't evil
 evil-emacs-state-cursor '("purple" box)
 ;; Always confirm (even on splash and other not "real" buffers)
 confirm-kill-emacs 'y-or-n-p
 projectile-project-search-path '("$HOME/src", "$HOME/org"))
;; Start fullscreen
(add-to-list 'initial-frame-alist '(fullscreen . maximized))
;; Doom exposes five (optional) variables for controlling fonts in Doom. Here
;; are the three important ones:
;;
;; + `doom-font'
;; + `doom-variable-pitch-font'
;; + `doom-big-font' -- used for `doom-big-font-mode'; use this for
;;   presentations or streaming.
;;
;; They all accept either a font-spec, font string ("Input Mono-12"), or xlfd
;; font string. You generally only need these two:
;; (setq doom-font (font-spec :family "monospace" :size 12 :weight 'semi-light)
;;       doom-variable-pitch-font (font-spec :family "sans" :size 13))

;; There are two ways to load a theme. Both assume the theme is installed and
;; available. You can either set `doom-theme' or manually load a theme with the
;; `load-theme' function. This is the default:
(setq doom-theme 'doom-tomorrow-night)

;; make it so horizontal scroll is not a thing
(setq-default truncate-lines nil)
(setq-default word-wrap t)
#+end_src
** Insertion methods
Japanese input
日本語！ テスト
#+begin_src elisp
(after! mozc
  (setq-default mozc-candidate-style 'echo-area))
#+end_src

** Line number styling
This determines the style of line numbers in effect. If set to `nil', line
numbers are disabled. For relative line numbers, set this to `relative'.

#+begin_src elisp
(setq display-line-numbers-type 'relative)
#+end_src

** Window System
*** Popup window styling
Default is way too small, bigger is better
#+begin_src elisp
(set-popup-rules!
  '(("^\\*\\([Hh]elp\\|Apropos\\)"
     :slot 2 :vslot -8 :size 0.45 :select t)))
#+end_src
*** Break window out into workspace
#+begin_src elisp
(defun break-window-into-workspace ()
  "Takes current window and moves it to its own workspace/perspective"
  (interactive)
  (let ((buff (current-buffer)))
    (+workspace/close-window-or-workspace)
    (+workspace/new)
    (switch-to-buffer buff)
    (when (+popup-buffer-p)
      (+popup/raise (selected-window)))))
(map! :leader
      :prefix "TAB"
      :nv "b" 'break-window-into-workspace) ; b for break
#+end_src

** Spell Checking
I'm currently using spell-fu bundled with doom.
+ Set dictionary to english
+ Ignore certain faces.
#+begin_src elisp
(setq-default ispell-dictionary "en")
(setq ispell-personal-dictionary "/home/brpol/.doom.d/etc/english.pws")
(setf (alist-get 'markdown-mode +spell-excluded-faces-alist)
      '(markdown-code-face
        markdown-reference-face
        markdown-link-face
        markdown-url-face
        markdown-markup-face
        markdown-html-attr-value-face
        markdown-html-attr-name-face
        markdown-html-tag-name-face))
#+end_src

** FUN STUFF!
*** Doom Dash
**** TODO if fancy splash displayed then emit Emacs in ascii
**** Code
This is mostly ripped from [[file:~/.emacs.d/modules/ui/doom-dashboard/config.el::defun doom-dashboard-draw-ascii-banner-fn (][Doom Dashboard]] itself.
#+begin_src elisp
(setq fancy-splash-image "~/.doom.d/logo.png")
(defun doom-dashboard-print-under-fancy-splash ()
  (when (display-graphic-p)
    (let* ((banner
            '(" _____                          "
              "| ____|_ __ ___   __ _  ___ ___ "
              "|  _| | '_ ` _ \\ / _` |/ __/ __|"
              "| |___| | | | | | (_| | (__\\__ \\"
              "|_____|_| |_| |_|\\__,_|\\___|___/"))
           (longest-line (apply #'max (mapcar #'length banner))))
      (put-text-property
       (point)
       (dolist (line banner (point))
         (insert (+doom-dashboard--center
                  +doom-dashboard--width
                  (concat
                   line (make-string (max 0 (- longest-line (length line)))
                                     32)))
                 "\n"))
       'face 'doom-dashboard-banner))))
(setq +doom-dashboard-functions
      '(doom-dashboard-widget-banner
        doom-dashboard-print-under-fancy-splash
        doom-dashboard-widget-shortmenu
        doom-dashboard-widget-loaded
        doom-dashboard-widget-footer))
#+end_src

* Custom (non mode specific) Bindings
Papa Henrik has a great [[https://github.com/hlissner/doom-emacs/blob/2d140a7a80996cd5d5abc084db995a8c4ab6d7f4/modules/config/default/%TBevil-bindings.el][DOOM Bindings Reference]]
** Global Bindings
Expand/contract visual mode selection
#+begin_src elisp
(map! :leader
      :prefix "v"
      :v "v" #'er/expand-region
      :v "SPC" #'er/contract-region)
#+end_src
** Lisp bindings
These help with navigation and movement in paren world
#+begin_src elisp
(map!
 :nvi "C-M-," 'sp-backward-slurp-sexp
 :nvi "C-M-." 'sp-forward-slurp-sexp
 :nvi "C-M-j" 'sp-beginning-of-next-sexp
 :nvi "C-M-k" 'sp-beginning-of-previous-sexp
 :nvi "C-M-u" 'backward-up-list
 :nvi "C-M-h" 'down-list)
#+end_src

* Modes
** Evil
*** Evil Easymotion
The default did not have enough avy-keys (jump keys, whatever)
#+begin_src elisp
(after! evil-easymotion
  ;; evil-easymotion (built on avy) jump keys
  (setq avy-keys '(?a ?s ?d ?f ?g ?h ?i ?k ?l ?\; ?t ?u ?v ?b ?n ?m ?i ?,))
  ;; evil-easymotion use first column
  (evilem-make-motion
   evilem-motion-next-line #'next-line
   :pre-hook (setq evil-this-type 'line)
   :bind ((temporary-goal-column 0)
          (line-move-visual nil)))
  (evilem-make-motion
   evilem-motion-previous-line #'previous-line
   :pre-hook (setq evil-this-type 'line)
   :bind ((temporary-goal-column 0)
          (line-move-visual nil))))
#+end_src

*** Evil Escape
Let me use jj to exit insert mode.
#+begin_src elisp
(use-package! evil-escape
  :init
  (setq evil-escape-delay 0.3)
  (setq evil-escape-key-sequence "jj"))
#+end_src
*** Ace Window
Make it so even rob can see window jumps
#+begin_src elisp
(custom-set-faces!
  '(aw-leading-char-face
    :foreground "white" :background "red"
    :weight bold :height 2.5 :box (:line-width 7 :color "red")))
#+end_src

** Org Mode
+ I set up my default org directory to be in home
+ I set up my TODOs to be more slick
+ Set up refiling to go deeeeeep
+ Turn of smartparens for org they make it hard to autocomplete links
#+begin_src elisp
(after! org
  ;; If you use `org' and don't want your org files in the default location below,
  ;; change `org-directory'. It must be set before org loads!
  (setq org-directory "~/org/"
        org-todo-keywords '((sequence "TODO(t)" "INPROGRESS(i)" "WAITING(w)" "|" "DONE(d)" "CANCELLED(c)")
                            (sequence "[ ](T)" "[-](S)" "[?](W)" "|" "[X](D)")
                            (sequence "|" "OKAY(o)" "YES(y)" "NO(n)"))
        org-todo-keyword-faces '(("TODO" :foreground "forestgreen" :weight bold :underline t)
                                 ("INPROGRESS" :foreground "darkorange" :weight bold :underline t)
                                 ("WAITING" :foreground "yellow" :weight normal :underline nil)
                                 ("CANCELLED" :foreground "red" :weight bold :underline t)
                                 )
        org-log-done 'time

        ;; Quick captures
        org-capture-templates '(("x" "[inbox]" entry
                                 (file+headline "~/org/inbox.org" "Tasks")
                                 "* %i%?")
                                ("t" "Todo [inbox]" entry
                                 (file+headline "~/org/inbox.org" "Tasks")
                                 "* TODO %i%?")
                                ("T" "Tickler" entry
                                 (file+headline "~/org/tickler.org" "Tickler")
                                 "* %i%? \n %U"))
        org-refile-targets '((nil :maxlevel . 4)
                             (org-agenda-files :maxlevel . 4))

        ;; Show that whitespace
        org-cycle-separator-lines -1
        ))

(after! (:and smartparens-mode org-mode)
  :init
  (add-hook 'org-mode-hook #'turn-off-smartparens-mode))
#+end_src

** Email mu4e
Inspired by: [[https://groups.google.com/g/mu-discuss/c/BpGtwVHMd2E][This Google Groups Post]]
*** Tasks
**** TODO create more mu4e-bookmarks for my tags in gmail
*** Code
#+begin_src elisp
(unless (eq system-type 'windows-nt)
  (after! mu4e
    :config
    (setq +mu4e-backend 'offlineimap)
    (setq mu4e-get-mail-command "offlineimap -o -q")
    (setq mu4e-index-update-error-continue t)
    (setq mu4e-index-update-error-warning t)
    (setq mu4e-root-maildir "~/mail")
    (setq mu4e-update-interval (* 60 5))
    (set-email-account! "Gmail"
                        '((mu4e-sent-folder       . "/Gmail/All Mail")
                          (mu4e-drafts-folder     . "/Gmail/Drafts")
                          (mu4e-trash-folder      . "/Gmail/Trash")
                          (mu4e-refile-folder     . "/Gmail/All Mail")
                          (smtpmail-smtp-user     . "brandonpollack23@gmail.com")
                          (user-mail-address      . "brandonpollack23@gmail.com")
                          (mu4e-compose-signature
                           . "---\nBrandon Pollack\n ブランドンポラック"))
                        t)
    (setq mu4e-bookmarks `(("x:\\\\Inbox" "Inbox" ?i)
                           ("x:\\\\Inbox AND flag:unread" "Inbox Unread" ?n)
                           ("flag:flagged" "Flagged messages" ?f)
                           (,(concat "flag:unread AND "
                                     "NOT flag:trashed AND "
                                     "NOT maildir:/[Gmail].Spam AND "
                                     "NOT maildir:/[Gmail].Bin")
                            "Unread messages" ?u)))
    (add-hook 'mu4e-mark-execute-pre-hook
              (lambda (mark msg)
                (cond ((member mark '(refile trash))
                       (mu4e-action-retag-message msg "-\\Inbox"))
                      ((equal mark 'flag)
                       (mu4e-action-retag-message msg "\\Starred"))
                      ((equal mark 'unflag)
                       (mu4e-action-retag-message msg "-\\Starred")))))
    ))
#+end_src

** Aggressive Indent
For Pretty code
#+begin_src elisp
(use-package! aggressive-indent
  :config
  (global-aggressive-indent-mode 1)
  (setq aggressive-indent-comments-too 1))
#+end_src

** Info Mode
Better font bigger text, yo
#+begin_src elisp
(defun my-buffer-face-mode-variable ()
  "Set font to a variable width (proportional) fonts in current buffer"
  (interactive)
  (setq buffer-face-mode-face '(:family "DejaVuSans" :height 150 :width semi-condensed))
  (buffer-face-mode))
(add-hook 'Info-mode-hook 'my-buffer-face-mode-variable)
#+end_src

* Platform Specific
** WSL
Web browser opening doesnt work without this
#+begin_src elisp
;; Determine the specific system type.
;; Emacs variable system-type doesn't yet have a "wsl/linux" value,
;; so I'm front-ending system-type with my variable: sysTypeSpecific.
;; I'm no elisp hacker, so I'm diverging from the elisp naming convention
;; to ensure that I'm not stepping on any pre-existing variable.
(setq-default sysTypeSpecific  system-type) ;; get the system-type value

(cond
 ;; If type is "gnu/linux", override to "wsl/linux" if it's WSL.
 ((eq sysTypeSpecific 'gnu/linux)
  (when (string-match "Linux.*Microsoft.*Linux"
                      (shell-command-to-string "uname -a"))

    (setq-default sysTypeSpecific "wsl/linux") ;; for later use.
    (setq
     cmdExeBin"/mnt/c/Windows/System32/cmd.exe"
     cmdExeArgs '("/c" "start"))
    (setq
     browse-url-generic-program  cmdExeBin
     browse-url-generic-args     cmdExeArgs
     browse-url-browser-function 'browse-url-generic)
    )))
#+end_src
