-- Feeds the GTK scripts (scripts/capture.py) the active theme. Every config load
-- writes the palette as GTK named colours to $XDG_STATE_HOME/hypr/colors.css,
-- one per palette key: `@define-color primary #bd93f9;`, used as @primary.
local theme = require("conf.theme")

local home = os.getenv("HOME")
local stateDir = (os.getenv("XDG_STATE_HOME") or (home .. "/.local/state")) .. "/hypr"

local lines = { "/* Generated by conf/gtk_colors.lua on every Hyprland config load; do not edit. */" }

-- theme.colors falls back to default.lua key by key, so walk the fallback's keys
-- to get every colour even when the selected theme leaves some out.
local confDir = debug.getinfo(1, "S").source:match("^@(.*)/[^/]+$")
local fallback = assert(loadfile(confDir .. "/themes/default.lua"))()
local names = {}
for key, value in pairs(fallback) do
	if type(value) == "string" and value:match("^#%x%x%x%x%x%x$") then
		names[#names + 1] = key
	end
end
table.sort(names)

for _, key in ipairs(names) do
	table.insert(lines, string.format("@define-color %s %s;", key, theme.colors[key]))
end

os.execute("mkdir -p '" .. stateDir .. "'")
local out = assert(io.open(stateDir .. "/colors.css", "w"))
out:write(table.concat(lines, "\n"), "\n")
out:close()
