-- Feeds hyprlock (hyprlock.conf) the active theme. hyprlock can't read Lua, so
-- every config load writes the palette as hyprlang variables to
-- $XDG_STATE_HOME/hypr/hyprlock.conf, which hyprlock.conf sources. Each palette
-- key becomes two variables:
--
--   $primary      = rgb(bd93f9)   for colour options
--   $primaryAlpha = bd93f9        for alpha, rgba($primaryAlphacc), and pango
--                                 markup, foreground="##$primaryAlpha"
--
-- Also sets $avatar to ~/.face when it exists, so the avatar widget stays empty
-- rather than erroring without one.
local theme = require("conf.theme")

local home = os.getenv("HOME")
local stateDir = (os.getenv("XDG_STATE_HOME") or (home .. "/.local/state")) .. "/hypr"
local outFile = stateDir .. "/hyprlock.conf"

local lines = { "# Generated by conf/lockscreen.lua on every Hyprland config load; do not edit." }

-- theme.colors falls back to default.lua key by key, so walk the fallback's keys
-- to get every colour even when the selected theme leaves some out.
local confDir = debug.getinfo(1, "S").source:match("^@(.*)/[^/]+$")
local fallback = assert(loadfile(confDir .. "/themes/default.lua"))()
local names = {}
for key, value in pairs(fallback) do
	if type(value) == "string" and value:match("^#%x%x%x%x%x%x$") then
		names[#names + 1] = key
	end
end
table.sort(names)

for _, key in ipairs(names) do
	local hex = theme.colors[key]:gsub("^#", "")
	table.insert(lines, string.format("$%s = rgb(%s)", key, hex))
	table.insert(lines, string.format("$%sAlpha = %s", key, hex))
end

local face = home .. "/.face"
local f = io.open(face)
if f then
	f:close()
	table.insert(lines, "$avatar = " .. face)
else
	table.insert(lines, "$avatar =")
end

os.execute("mkdir -p '" .. stateDir .. "'")
local out = assert(io.open(outFile, "w"))
out:write(table.concat(lines, "\n"), "\n")
out:close()
