#!/usr/bin/env bash
#MISE description="Install the fonts in fonts/"
set -euo pipefail
if [[ "$OSTYPE" == darwin* ]]; then
  dir=~/Library/Fonts
else
  dir=${XDG_DATA_HOME:-$HOME/.local/share}/fonts
fi
mkdir -p "$dir"
cp -v "$MISE_CONFIG_ROOT"/fonts/*.ttf "$dir/"
if command -v fc-cache >/dev/null; then fc-cache -f "$dir"; fi
